server:
    port: 8082
    servlet:
        context-path: /user-service

spring:
    application:
        name: user-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka